version: '3.8'
services:    
    wordpress:
        image: wordpress:latest
        build: ./wp
        container_name: ${COMPOSE_PROJECT_NAME:-wp-only}
        volumes:
            - ./config/php.conf.ini:/usr/local/etc/php/conf.d/php.ini
            - ./wordpress:/var/www/html
        environment:
            - WORDPRESS_DB_NAME=wp_docker
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DB_HOST=host.docker.internal
            - WORDPRESS_DB_USER=wp
            - WORDPRESS_DB_PASSWORD=wpPassword123
        restart: always
        ports:
                - 8080:80

    healthcheck:
        image: wpcli
        build: ./wpcli/
        container_name: ${COMPOSE_PROJECT_NAME}-wp-only-healthcheck
        command: sh -c "/wait"
        environment:
            - WAIT_HOSTS=host.docker.internal:3306, wordpress:80
            - WAIT_BEFORE_HOSTS=${WAIT_BEFORE_HOSTS:-30}
            - WAIT_AFTER_HOSTS=${WAIT_AFTER_HOSTS:-15}
            - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT:-300}
            - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL:-30}
            - WAIT_HOST_CONNECT_TIMEOUT=${WAIT_HOST_CONNECT_TIMEOUT:-30}
